-- phpMyAdmin SQL Dump
-- version 3.3.9.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Feb 10, 2018 at 12:14 PM
-- Server version: 5.5.9
-- PHP Version: 5.3.5

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `TavantPoolWeekDay`
--

-- --------------------------------------------------------

--
-- Table structure for table `BookingInfo`
--

CREATE TABLE `BookingInfo` (
  `ownerEmail` varchar(50) NOT NULL,
  `isBooked` int(11) NOT NULL,
  `isPending` int(11) NOT NULL,
  `isExpired` int(11) NOT NULL,
  `seatsBooked` int(11) NOT NULL,
  `totalSeatsOffered` int(11) NOT NULL,
  `bookieEmail` varchar(50) NOT NULL,
  `bookiePhoneNumber` varchar(15) NOT NULL,
  `bookedTripID` bigint(20) NOT NULL,
  `message` mediumtext NOT NULL,
  `messageTag` int(11) NOT NULL,
  `deviceToken` varchar(100) NOT NULL,
  `ownerPhoneNumber` varchar(15) NOT NULL,
  `deviceType` int(11) NOT NULL,
  `bookieName` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `BookingInfo`
--

INSERT INTO `BookingInfo` VALUES('navanitha.p@tavant.com', 0, 1, 0, 1, 4, 'anusha.surendra@tavant.com', '9898765432', 1481787365, '', 0, '', '9898765432', 1, 'Anusha Surendra');
INSERT INTO `BookingInfo` VALUES('kevin.saldanha@tavant.com', 1, 0, 0, 4, 6, 'navanitha.p@tavant.com', '9898765432', 1481659833, '', 0, '', '9898765432', 1, 'Navanitha P');
INSERT INTO `BookingInfo` VALUES('', 0, 1, 0, 0, 0, '', '', 0, '', 0, '', '', 0, '');

-- --------------------------------------------------------

--
-- Table structure for table `LatLongs`
--

CREATE TABLE `LatLongs` (
  `latitude` double NOT NULL,
  `longitude` double NOT NULL,
  `routeId` bigint(20) NOT NULL,
  `distance` mediumtext NOT NULL,
  `duration` mediumtext NOT NULL,
  `htmlImstruction` mediumtext NOT NULL,
  `polyline` longtext NOT NULL,
  `orderID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `LatLongs`
--

INSERT INTO `LatLongs` VALUES(12.8086272, 74.8944415, 1481721460, '4.5 km', '9 mins', 'Head northwest on Mangalore-Thokkottu-Konaje Univarsity Rd/University Rd toward Beeri Derlakatte RdContinue to follow Mangalore-Thokkottu-Konaje Univarsity RdPass by Adarsh Bldg (on the right)', '}tdmAgybhMm@`Cu@nC[nAQpAO|AAf@@pALpBHxDLjHDlIExAGRSf@yCxFqChEmAtBc@~@o@`Ak@VoBt@oAz@{A~@oBtAmAn@cCVyE`@qANoAZcBh@}Ap@oDdBoAr@[TGF@j@AvB]nFMlAUpB}@rGgAfEKt@Ip@YfAWp@UbAH~AP~Ap@jBtApDdAjCl@zALj@`@~BRp@X~@`AtCNz@BlAEdAIl@WlA_@bAY|@SbAGtAF`BDp@RzAr@|BpAfDaAb@g@FQHOLGv@Hj@`@j@LDJFc@CgJ}@uIaAUBw@IgBQmBK}GIkBC{CA{EKoQi@oDMeDM{@Gq@AiD@cHT_w@pBcCFeC?qBKw@GaAYs@YwAu@oAu@yAeAkF}DcHyEoCqB_GsE{PeNuB}@i@SgAK{@AeBFkCPaBLq@Jy@JkK|AgCeBLqJr@wEX_BRqA`@q@cE`CoC`Bg@`@a@Zo@`@?DA@ABEHGJKDI@[AQKCCkBRaBFyBIyD[uASoAa@uA]qEwAqFiBmAQmAEoALc@LqAiDzA}D~AkAZsANoCC_BIuCS}DW_@?s@Di@NYLSR]f@@HENKLS@GACAoBl@_HxD}BrAyAhAiA`AoB~Bs@bAc@|@s@vAq@nBwBhI}B`JsAtFO~@@FADKHE@ER[dAi@`Bi@jBsA|F]rAk@rAq@pAa@j@g@b@wBxA}Ax@cAt@s@t@_BxAaFvDgA`AONCJGRQRgD~CgDtC{E`EOQUYa@_@iAk@_AY{AYsA_@iE_BqA_@uA[kB]iAe@oAy@[]g@c@WOy@YeAa@aAs@q@s@g@u@eAuAw@iBqBgGWg@SUMKg@W[ISCeAKWMWOKMc@{@]aAWg@SO{Ac@_Cw@K_@Ec@N}ABsACaBGs@[e@WO_@IoAIqAScBk@a@Oo@]oByAw@]oBo@', 0);
INSERT INTO `LatLongs` VALUES(12.8182434, 74.8603755, 1481721460, '0.2 km', '1 min', 'Turn right at Boomika Complex onto Thokottu Bus Stand Rd', '}tdmAgybhMm@`Cu@nC[nAQpAO|AAf@@pALpBHxDLjHDlIExAGRSf@yCxFqChEmAtBc@~@o@`Ak@VoBt@oAz@{A~@oBtAmAn@cCVyE`@qANoAZcBh@}Ap@oDdBoAr@[TGF@j@AvB]nFMlAUpB}@rGgAfEKt@Ip@YfAWp@UbAH~AP~Ap@jBtApDdAjCl@zALj@`@~BRp@X~@`AtCNz@BlAEdAIl@WlA_@bAY|@SbAGtAF`BDp@RzAr@|BpAfDaAb@g@FQHOLGv@Hj@`@j@LDJFc@CgJ}@uIaAUBw@IgBQmBK}GIkBC{CA{EKoQi@oDMeDM{@Gq@AiD@cHT_w@pBcCFeC?qBKw@GaAYs@YwAu@oAu@yAeAkF}DcHyEoCqB_GsE{PeNuB}@i@SgAK{@AeBFkCPaBLq@Jy@JkK|AgCeBLqJr@wEX_BRqA`@q@cE`CoC`Bg@`@a@Zo@`@?DA@ABEHGJKDI@[AQKCCkBRaBFyBIyD[uASoAa@uA]qEwAqFiBmAQmAEoALc@LqAiDzA}D~AkAZsANoCC_BIuCS}DW_@?s@Di@NYLSR]f@@HENKLS@GACAoBl@_HxD}BrAyAhAiA`AoB~Bs@bAc@|@s@vAq@nBwBhI}B`JsAtFO~@@FADKHE@ER[dAi@`Bi@jBsA|F]rAk@rAq@pAa@j@g@b@wBxA}Ax@cAt@s@t@_BxAaFvDgA`AONCJGRQRgD~CgDtC{E`EOQUYa@_@iAk@_AY{AYsA_@iE_BqA_@uA[kB]iAe@oAy@[]g@c@WOy@YeAa@aAs@q@s@g@u@eAuAw@iBqBgGWg@SUMKg@W[ISCeAKWMWOKMc@{@]aAWg@SO{Ac@_Cw@K_@Ec@N}ABsACaBGs@[e@WO_@IoAIqAScBk@a@Oo@]oByAw@]oBo@', 1);
INSERT INTO `LatLongs` VALUES(12.8187557, 74.8593157, 1481721460, '43 m', '1 min', 'Continue straight past Panchayat Bldg', '}tdmAgybhMm@`Cu@nC[nAQpAO|AAf@@pALpBHxDLjHDlIExAGRSf@yCxFqChEmAtBc@~@o@`Ak@VoBt@oAz@{A~@oBtAmAn@cCVyE`@qANoAZcBh@}Ap@oDdBoAr@[TGF@j@AvB]nFMlAUpB}@rGgAfEKt@Ip@YfAWp@UbAH~AP~Ap@jBtApDdAjCl@zALj@`@~BRp@X~@`AtCNz@BlAEdAIl@WlA_@bAY|@SbAGtAF`BDp@RzAr@|BpAfDaAb@g@FQHOLGv@Hj@`@j@LDJFc@CgJ}@uIaAUBw@IgBQmBK}GIkBC{CA{EKoQi@oDMeDM{@Gq@AiD@cHT_w@pBcCFeC?qBKw@GaAYs@YwAu@oAu@yAeAkF}DcHyEoCqB_GsE{PeNuB}@i@SgAK{@AeBFkCPaBLq@Jy@JkK|AgCeBLqJr@wEX_BRqA`@q@cE`CoC`Bg@`@a@Zo@`@?DA@ABEHGJKDI@[AQKCCkBRaBFyBIyD[uASoAa@uA]qEwAqFiBmAQmAEoALc@LqAiDzA}D~AkAZsANoCC_BIuCS}DW_@?s@Di@NYLSR]f@@HENKLS@GACAoBl@_HxD}BrAyAhAiA`AoB~Bs@bAc@|@s@vAq@nBwBhI}B`JsAtFO~@@FADKHE@ER[dAi@`Bi@jBsA|F]rAk@rAq@pAa@j@g@b@wBxA}Ax@cAt@s@t@_BxAaFvDgA`AONCJGRQRgD~CgDtC{E`EOQUYa@_@iAk@_AY{AYsA_@iE_BqA_@uA[kB]iAe@oAy@[]g@c@WOy@YeAa@aAs@q@s@g@u@eAuAw@iBqBgGWg@SUMKg@W[ISCeAKWMWOKMc@{@]aAWg@SO{Ac@_Cw@K_@Ec@N}ABsACaBGs@[e@WO_@IoAIqAScBk@a@Oo@]oByAw@]oBo@', 2);
INSERT INTO `LatLongs` VALUES(12.8185863, 74.8589882, 1481721460, '6.0 km', '9 mins', 'Sharp right onto NH66Pass by Aarisha Complex (on the right)', '}tdmAgybhMm@`Cu@nC[nAQpAO|AAf@@pALpBHxDLjHDlIExAGRSf@yCxFqChEmAtBc@~@o@`Ak@VoBt@oAz@{A~@oBtAmAn@cCVyE`@qANoAZcBh@}Ap@oDdBoAr@[TGF@j@AvB]nFMlAUpB}@rGgAfEKt@Ip@YfAWp@UbAH~AP~Ap@jBtApDdAjCl@zALj@`@~BRp@X~@`AtCNz@BlAEdAIl@WlA_@bAY|@SbAGtAF`BDp@RzAr@|BpAfDaAb@g@FQHOLGv@Hj@`@j@LDJFc@CgJ}@uIaAUBw@IgBQmBK}GIkBC{CA{EKoQi@oDMeDM{@Gq@AiD@cHT_w@pBcCFeC?qBKw@GaAYs@YwAu@oAu@yAeAkF}DcHyEoCqB_GsE{PeNuB}@i@SgAK{@AeBFkCPaBLq@Jy@JkK|AgCeBLqJr@wEX_BRqA`@q@cE`CoC`Bg@`@a@Zo@`@?DA@ABEHGJKDI@[AQKCCkBRaBFyBIyD[uASoAa@uA]qEwAqFiBmAQmAEoALc@LqAiDzA}D~AkAZsANoCC_BIuCS}DW_@?s@Di@NYLSR]f@@HENKLS@GACAoBl@_HxD}BrAyAhAiA`AoB~Bs@bAc@|@s@vAq@nBwBhI}B`JsAtFO~@@FADKHE@ER[dAi@`Bi@jBsA|F]rAk@rAq@pAa@j@g@b@wBxA}Ax@cAt@s@t@_BxAaFvDgA`AONCJGRQRgD~CgDtC{E`EOQUYa@_@iAk@_AY{AYsA_@iE_BqA_@uA[kB]iAe@oAy@[]g@c@WOy@YeAa@aAs@q@s@g@u@eAuAw@iBqBgGWg@SUMKg@W[ISCeAKWMWOKMc@{@]aAWg@SO{Ac@_Cw@K_@Ec@N}ABsACaBGs@[e@WO_@IoAIqAScBk@a@Oo@]oByAw@]oBo@', 3);
INSERT INTO `LatLongs` VALUES(12.8688861, 74.8640298, 1481721460, '1.7 km', '3 mins', 'At Mahaveer Cir, take the 3rd exit and stay on NH66Pass by Vishwas View Bldg (on the left in 450&nbsp;m)', '}tdmAgybhMm@`Cu@nC[nAQpAO|AAf@@pALpBHxDLjHDlIExAGRSf@yCxFqChEmAtBc@~@o@`Ak@VoBt@oAz@{A~@oBtAmAn@cCVyE`@qANoAZcBh@}Ap@oDdBoAr@[TGF@j@AvB]nFMlAUpB}@rGgAfEKt@Ip@YfAWp@UbAH~AP~Ap@jBtApDdAjCl@zALj@`@~BRp@X~@`AtCNz@BlAEdAIl@WlA_@bAY|@SbAGtAF`BDp@RzAr@|BpAfDaAb@g@FQHOLGv@Hj@`@j@LDJFc@CgJ}@uIaAUBw@IgBQmBK}GIkBC{CA{EKoQi@oDMeDM{@Gq@AiD@cHT_w@pBcCFeC?qBKw@GaAYs@YwAu@oAu@yAeAkF}DcHyEoCqB_GsE{PeNuB}@i@SgAK{@AeBFkCPaBLq@Jy@JkK|AgCeBLqJr@wEX_BRqA`@q@cE`CoC`Bg@`@a@Zo@`@?DA@ABEHGJKDI@[AQKCCkBRaBFyBIyD[uASoAa@uA]qEwAqFiBmAQmAEoALc@LqAiDzA}D~AkAZsANoCC_BIuCS}DW_@?s@Di@NYLSR]f@@HENKLS@GACAoBl@_HxD}BrAyAhAiA`AoB~Bs@bAc@|@s@vAq@nBwBhI}B`JsAtFO~@@FADKHE@ER[dAi@`Bi@jBsA|F]rAk@rAq@pAa@j@g@b@wBxA}Ax@cAt@s@t@_BxAaFvDgA`AONCJGRQRgD~CgDtC{E`EOQUYa@_@iAk@_AY{AYsA_@iE_BqA_@uA[kB]iAe@oAy@[]g@c@WOy@YeAa@aAs@q@s@g@u@eAuAw@iBqBgGWg@SUMKg@W[ISCeAKWMWOKMc@{@]aAWg@SO{Ac@_Cw@K_@Ec@N}ABsACaBGs@[e@WO_@IoAIqAScBk@a@Oo@]oByAw@]oBo@', 4);
INSERT INTO `LatLongs` VALUES(12.8837122, 74.8638381, 1481721460, '2.5 km', '4 mins', 'At Kulathoor Jct/Nanthoor Jct, take the 2nd exit and stay on NH66Pass by CR Complex (on the left)', '}tdmAgybhMm@`Cu@nC[nAQpAO|AAf@@pALpBHxDLjHDlIExAGRSf@yCxFqChEmAtBc@~@o@`Ak@VoBt@oAz@{A~@oBtAmAn@cCVyE`@qANoAZcBh@}Ap@oDdBoAr@[TGF@j@AvB]nFMlAUpB}@rGgAfEKt@Ip@YfAWp@UbAH~AP~Ap@jBtApDdAjCl@zALj@`@~BRp@X~@`AtCNz@BlAEdAIl@WlA_@bAY|@SbAGtAF`BDp@RzAr@|BpAfDaAb@g@FQHOLGv@Hj@`@j@LDJFc@CgJ}@uIaAUBw@IgBQmBK}GIkBC{CA{EKoQi@oDMeDM{@Gq@AiD@cHT_w@pBcCFeC?qBKw@GaAYs@YwAu@oAu@yAeAkF}DcHyEoCqB_GsE{PeNuB}@i@SgAK{@AeBFkCPaBLq@Jy@JkK|AgCeBLqJr@wEX_BRqA`@q@cE`CoC`Bg@`@a@Zo@`@?DA@ABEHGJKDI@[AQKCCkBRaBFyBIyD[uASoAa@uA]qEwAqFiBmAQmAEoALc@LqAiDzA}D~AkAZsANoCC_BIuCS}DW_@?s@Di@NYLSR]f@@HENKLS@GACAoBl@_HxD}BrAyAhAiA`AoB~Bs@bAc@|@s@vAq@nBwBhI}B`JsAtFO~@@FADKHE@ER[dAi@`Bi@jBsA|F]rAk@rAq@pAa@j@g@b@wBxA}Ax@cAt@s@t@_BxAaFvDgA`AONCJGRQRgD~CgDtC{E`EOQUYa@_@iAk@_AY{AYsA_@iE_BqA_@uA[kB]iAe@oAy@[]g@c@WOy@YeAa@aAs@q@s@g@u@eAuAw@iBqBgGWg@SUMKg@W[ISCeAKWMWOKMc@{@]aAWg@SO{Ac@_Cw@K_@Ec@N}ABsACaBGs@[e@WO_@IoAIqAScBk@a@Oo@]oByAw@]oBo@', 5);
INSERT INTO `LatLongs` VALUES(12.8964481, 74.8465136, 1481721460, '0.4 km', '1 min', 'Take the exit toward Bajpe Rd/Bejai - Kavoor Rd', '}tdmAgybhMm@`Cu@nC[nAQpAO|AAf@@pALpBHxDLjHDlIExAGRSf@yCxFqChEmAtBc@~@o@`Ak@VoBt@oAz@{A~@oBtAmAn@cCVyE`@qANoAZcBh@}Ap@oDdBoAr@[TGF@j@AvB]nFMlAUpB}@rGgAfEKt@Ip@YfAWp@UbAH~AP~Ap@jBtApDdAjCl@zALj@`@~BRp@X~@`AtCNz@BlAEdAIl@WlA_@bAY|@SbAGtAF`BDp@RzAr@|BpAfDaAb@g@FQHOLGv@Hj@`@j@LDJFc@CgJ}@uIaAUBw@IgBQmBK}GIkBC{CA{EKoQi@oDMeDM{@Gq@AiD@cHT_w@pBcCFeC?qBKw@GaAYs@YwAu@oAu@yAeAkF}DcHyEoCqB_GsE{PeNuB}@i@SgAK{@AeBFkCPaBLq@Jy@JkK|AgCeBLqJr@wEX_BRqA`@q@cE`CoC`Bg@`@a@Zo@`@?DA@ABEHGJKDI@[AQKCCkBRaBFyBIyD[uASoAa@uA]qEwAqFiBmAQmAEoALc@LqAiDzA}D~AkAZsANoCC_BIuCS}DW_@?s@Di@NYLSR]f@@HENKLS@GACAoBl@_HxD}BrAyAhAiA`AoB~Bs@bAc@|@s@vAq@nBwBhI}B`JsAtFO~@@FADKHE@ER[dAi@`Bi@jBsA|F]rAk@rAq@pAa@j@g@b@wBxA}Ax@cAt@s@t@_BxAaFvDgA`AONCJGRQRgD~CgDtC{E`EOQUYa@_@iAk@_AY{AYsA_@iE_BqA_@uA[kB]iAe@oAy@[]g@c@WOy@YeAa@aAs@q@s@g@u@eAuAw@iBqBgGWg@SUMKg@W[ISCeAKWMWOKMc@{@]aAWg@SO{Ac@_Cw@K_@Ec@N}ABsACaBGs@[e@WO_@IoAIqAScBk@a@Oo@]oByAw@]oBo@', 6);
INSERT INTO `LatLongs` VALUES(12.8992953, 74.8438077, 1481721460, '2.3 km', '4 mins', 'Turn right at Kuntikana Jct onto Bajpe Rd/Bejai - Kavoor RdPass by Emporous Apartments (on the left)', '}tdmAgybhMm@`Cu@nC[nAQpAO|AAf@@pALpBHxDLjHDlIExAGRSf@yCxFqChEmAtBc@~@o@`Ak@VoBt@oAz@{A~@oBtAmAn@cCVyE`@qANoAZcBh@}Ap@oDdBoAr@[TGF@j@AvB]nFMlAUpB}@rGgAfEKt@Ip@YfAWp@UbAH~AP~Ap@jBtApDdAjCl@zALj@`@~BRp@X~@`AtCNz@BlAEdAIl@WlA_@bAY|@SbAGtAF`BDp@RzAr@|BpAfDaAb@g@FQHOLGv@Hj@`@j@LDJFc@CgJ}@uIaAUBw@IgBQmBK}GIkBC{CA{EKoQi@oDMeDM{@Gq@AiD@cHT_w@pBcCFeC?qBKw@GaAYs@YwAu@oAu@yAeAkF}DcHyEoCqB_GsE{PeNuB}@i@SgAK{@AeBFkCPaBLq@Jy@JkK|AgCeBLqJr@wEX_BRqA`@q@cE`CoC`Bg@`@a@Zo@`@?DA@ABEHGJKDI@[AQKCCkBRaBFyBIyD[uASoAa@uA]qEwAqFiBmAQmAEoALc@LqAiDzA}D~AkAZsANoCC_BIuCS}DW_@?s@Di@NYLSR]f@@HENKLS@GACAoBl@_HxD}BrAyAhAiA`AoB~Bs@bAc@|@s@vAq@nBwBhI}B`JsAtFO~@@FADKHE@ER[dAi@`Bi@jBsA|F]rAk@rAq@pAa@j@g@b@wBxA}Ax@cAt@s@t@_BxAaFvDgA`AONCJGRQRgD~CgDtC{E`EOQUYa@_@iAk@_AY{AYsA_@iE_BqA_@uA[kB]iAe@oAy@[]g@c@WOy@YeAa@aAs@q@s@g@u@eAuAw@iBqBgGWg@SUMKg@W[ISCeAKWMWOKMc@{@]aAWg@SO{Ac@_Cw@K_@Ec@N}ABsACaBGs@[e@WO_@IoAIqAScBk@a@Oo@]oByAw@]oBo@', 7);
INSERT INTO `LatLongs` VALUES(12.910475, 77.5856988, 1481787365, '0.6 km', '2 mins', 'Head north on 24th Main Rd toward 9th Cross Rd', 'oqxmAsmpxMqKGiHCeLGc@rIIrA}BFOFSAe@BoHAoEC_CK{B?cCCmEAuH?i@Ku@?yA@{AAoBDkCn@}@Hq@?aAMqC_AwD@kDGeA@iGCgDEAF', 0);
INSERT INTO `LatLongs` VALUES(12.9160907, 77.5857973, 1481787365, '0.2 km', '1 min', 'Turn left onto 47th Cross Rd', 'oqxmAsmpxMqKGiHCeLGc@rIIrA}BFOFSAe@BoHAoEC_CK{B?cCCmEAuH?i@Ku@?yA@{AAoBDkCn@}@Hq@?aAMqC_AwD@kDGeA@iGCgDEAF', 0);
INSERT INTO `LatLongs` VALUES(12.9163198, 77.5836757, 1481787365, '0.9 km', '3 mins', 'Turn right onto 9th Main RdPass by Athityam (on the left in 500&nbsp;m)', 'oqxmAsmpxMqKGiHCeLGc@rIIrA}BFOFSAe@BoHAoEC_CK{B?cCCmEAuH?i@Ku@?yA@{AAoBDkCn@}@Hq@?aAMqC_AwD@kDGeA@iGCgDEAF', 0);
INSERT INTO `LatLongs` VALUES(12.9245938, 77.5837697, 1481787365, '0.9 km', '4 mins', 'Continue onto 9th Main RdPass by United Commercial Bank (on the right in 800&nbsp;m)', 'oqxmAsmpxMqKGiHCeLGc@rIIrA}BFOFSAe@BoHAoEC_CK{B?cCCmEAuH?i@Ku@?yA@{AAoBDkCn@}@Hq@?aAMqC_AwD@kDGeA@iGCgDEAF', 0);
INSERT INTO `LatLongs` VALUES(12.9329549, 77.5839141, 1481787365, '5 m', '1 min', 'Turn left onto Aurobindo Marg', 'oqxmAsmpxMqKGiHCeLGc@rIIrA}BFOFSAe@BoHAoEC_CK{B?cCCmEAuH?i@Ku@?yA@{AAoBDkCn@}@Hq@?aAMqC_AwD@kDGeA@iGCgDEAF', 0);
INSERT INTO `LatLongs` VALUES(12.9342921, 77.6202942, 1481792939, '43 m', '1 min', 'Head west on 2nd Cross Rd toward 17th C Main Rd', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.9343096, 77.6198968, 1481792939, '71 m', '1 min', 'Turn left onto 17th C Main Rd', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.9337509, 77.6195855, 1481792939, '0.3 km', '1 min', 'Turn right onto 1st A Cross Rd/60 Feet Rd/Krishna Temple RdContinue to follow 1st A Cross RdPass by PMR Hall (on the left)', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.9341322, 77.6166827, 1481792939, '0.4 km', '2 mins', 'Turn left onto Jyoti Nivas College Rd', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.9325169, 77.6135791, 1481792939, '11 m', '1 min', 'Continue straight to stay on Jyoti Nivas College Rd', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.932474, 77.6134857, 1481792939, '0.4 km', '2 mins', 'Turn left onto Hosur Rd', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.92951, 77.615193, 1481792939, '0.3 km', '1 min', 'Sharp right to stay on Hosur RdPass by the church (on the left)', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.9342921, 77.6202942, 1481659833, '43 m', '1 min', 'Head west on 2nd Cross Rd toward 17th C Main Rd', 'if}mAyewxMClAeAe@gCgAk@bAkAbCe@l@_C~Ew@k@u@[{A_@{@UsAk@eAe@q@YwG_Ea@n@s@fBqApCdAn@O`BAj@AxA_CGKdFE`ASdA_AdC_AzB[|@]bBIXSTKTQv@', 0);
INSERT INTO `LatLongs` VALUES(12.9343096, 77.6198968, 1481659833, '0.1 km', '1 min', 'Turn right onto 17th C Main Rd', 'if}mAyewxMClAeAe@gCgAk@bAkAbCe@l@_C~Ew@k@u@[{A_@{@UsAk@eAe@q@YwG_Ea@n@s@fBqApCdAn@O`BAj@AxA_CGKdFE`ASdA_AdC_AzB[|@]bBIXSTKTQv@', 0);
INSERT INTO `LatLongs` VALUES(12.9353396, 77.6204477, 1481659833, '0.3 km', '1 min', 'Turn left onto 3rd Cross Rd', 'if}mAyewxMClAeAe@gCgAk@bAkAbCe@l@_C~Ew@k@u@[{A_@{@UsAk@eAe@q@YwG_Ea@n@s@fBqApCdAn@O`BAj@AxA_CGKdFE`ASdA_AdC_AzB[|@]bBIXSTKTQv@', 0);
INSERT INTO `LatLongs` VALUES(12.9367675, 77.6180977, 1481659833, '0.5 km', '1 min', 'Turn right onto 20th Main Rd/Ganapathi Temple RdPass by the park (on the right in 350&nbsp;m)', 'if}mAyewxMClAeAe@gCgAk@bAkAbCe@l@_C~Ew@k@u@[{A_@{@UsAk@eAe@q@YwG_Ea@n@s@fBqApCdAn@O`BAj@AxA_CGKdFE`ASdA_AdC_AzB[|@]bBIXSTKTQv@', 0);
INSERT INTO `LatLongs` VALUES(12.9404986, 77.6202318, 1481659833, '0.2 km', '1 min', 'Turn left onto Adugodi Main Rd', 'if}mAyewxMClAeAe@gCgAk@bAkAbCe@l@_C~Ew@k@u@[{A_@{@UsAk@eAe@q@YwG_Ea@n@s@fBqApCdAn@O`BAj@AxA_CGKdFE`ASdA_AdC_AzB[|@]bBIXSTKTQv@', 0);
INSERT INTO `LatLongs` VALUES(12.9413371, 77.6187379, 1481659833, '46 m', '1 min', 'Turn left to stay on Adugodi Main Rd', 'if}mAyewxMClAeAe@gCgAk@bAkAbCe@l@_C~Ew@k@u@[{A_@{@UsAk@eAe@q@YwG_Ea@n@s@fBqApCdAn@O`BAj@AxA_CGKdFE`ASdA_AdC_AzB[|@]bBIXSTKTQv@', 0);
INSERT INTO `LatLongs` VALUES(12.9409926, 77.618503, 1481659833, '0.1 km', '1 min', 'Turn right to stay on Adugodi Main Rd', 'if}mAyewxMClAeAe@gCgAk@bAkAbCe@l@_C~Ew@k@u@[{A_@{@UsAk@eAe@q@YwG_Ea@n@s@fBqApCdAn@O`BAj@AxA_CGKdFE`ASdA_AdC_AzB[|@]bBIXSTKTQv@', 0);
INSERT INTO `LatLongs` VALUES(12.9410881, 77.6173408, 1481659833, '72 m', '1 min', 'Turn right to stay on Adugodi Main Rd', 'if}mAyewxMClAeAe@gCgAk@bAkAbCe@l@_C~Ew@k@u@[{A_@{@UsAk@eAe@q@YwG_Ea@n@s@fBqApCdAn@O`BAj@AxA_CGKdFE`ASdA_AdC_AzB[|@]bBIXSTKTQv@', 0);
INSERT INTO `LatLongs` VALUES(12.9417342, 77.6173759, 1481659833, '0.5 km', '2 mins', 'Turn left onto Adugodi Main Rd/Koramangala RdPass by More For You (on the right)', 'if}mAyewxMClAeAe@gCgAk@bAkAbCe@l@_C~Ew@k@u@[{A_@{@UsAk@eAe@q@YwG_Ea@n@s@fBqApCdAn@O`BAj@AxA_CGKdFE`ASdA_AdC_AzB[|@]bBIXSTKTQv@', 0);
INSERT INTO `LatLongs` VALUES(12.9588194, 77.6971792, 1481783214, '0.2 km', '1 min', 'Head south on 5th Cross Rd', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9572655, 77.6969484, 1481783214, '73 m', '1 min', 'Turn left toward 9th Cross Rd', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9570125, 77.6975575, 1481783214, '18 m', '1 min', 'Turn right onto 9th Cross Rd', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9568466, 77.6975575, 1481783214, '0.4 km', '3 mins', 'Turn left onto H A L Old Airport Rd/Marathahalli Main Rd/Varthur Main RdPass by Louis Philippe Factory Outlet (on the right)', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9569693, 77.7012652, 1481783214, '0.4 km', '1 min', 'Turn right toward NH44', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9533531, 77.7003715, 1481783214, '6.8 km', '10 mins', 'Take the ramp on the right onto NH44Pass by VIMS Super Specialty Hospital (on the left in 550&nbsp;m)', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9237183, 77.6540827, 1481783214, '0.2 km', '1 min', 'Slight right toward Sarjapur Main Rd', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9242274, 77.6518536, 1481783214, '0.2 km', '1 min', 'Keep right to continue toward Sarjapur Main Rd', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.924442, 77.6501267, 1481783214, '2.1 km', '6 mins', 'Turn right onto Sarjapur Main RdPass by Karthikshekar Hospital (on the left in 1.3&nbsp;km)', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9244068, 77.6314529, 1481783214, '0.3 km', '1 min', 'Turn left', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9215248, 77.6318798, 1481783214, '0.2 km', '1 min', 'Turn right', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9230859, 77.6304471, 1481783214, '0.3 km', '1 min', 'Sharp left', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.920781, 77.6308604, 1481783214, '0.1 km', '1 min', 'Turn right', 's_bnAkffyMnBXb@B~@@dAFZDRUT_AHc@P@LAEc@Gg@Cc@a@kEAa@HuENqCB_@N?ZKJDlFlAlLjBh@b@`Ft@lBRxNxAtC`@pB^fEbApCr@rLvCrAZt@TfA`@rFrCd@P~Av@dEzBjC~ApBfB`FnFjC|C|NhPfJdKxJfLp@~@h@`Ar@|A~AdEvFlOdBrE^z@vGvQ|@~B~C`I^jAp@tBbE|LtCbIpCdHdFbNV|@BV@VAt@Ir@Kl@_BzI]bBcAzGa@zBo@hCaCfJcB`He@pCOlA_@tDQb@_@jCw@`H]|CEt@AnBSZGNIp@Cv@?~@HxBJrFJ`C@dFF|@FZHZvAvGhArGBFZ?TEwAjFkBjG_@v@s@hAk@lAWr@Kd@MdAATf@xFn@pGHxAb@fF`@hEtCUvDQzCc@vAIyH|GnBW|Iy@VhDBd@', 0);
INSERT INTO `LatLongs` VALUES(12.9342921, 77.6202942, 1482039451, '43 m', '1 min', 'Head west on 2nd Cross Rd toward 17th C Main Rd', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.9343096, 77.6198968, 1482039451, '71 m', '1 min', 'Turn left onto 17th C Main Rd', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.9337509, 77.6195855, 1482039451, '0.3 km', '1 min', 'Turn right onto 1st A Cross Rd/60 Feet Rd/Krishna Temple RdContinue to follow 1st A Cross RdPass by PMR Hall (on the left)', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.9341322, 77.6166827, 1482039451, '0.4 km', '2 mins', 'Turn left onto Jyoti Nivas College Rd', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.9325169, 77.6135791, 1482039451, '11 m', '1 min', 'Continue straight to stay on Jyoti Nivas College Rd', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.932474, 77.6134857, 1482039451, '0.4 km', '2 mins', 'Turn left onto Hosur Rd', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.92951, 77.615193, 1482039451, '0.3 km', '1 min', 'Sharp right to stay on Hosur RdPass by the church (on the left)', 'if}mAyewxMClAnB|@HvBhCGj@_AbDYnAQb@rAtC|BjFnBhFHP|CmAbF}BjAm@`Am@~@k@JV_FpCwCjAu@r@]ZUTmBhC}FrIsBfDyAlBy@tAiDrGw@zBc@bBSpAc@fGUlCOzBB`@?VS|CQ|AJNV^Zb@FpBVVHLJzBJnBNjN`BvPh@|LNnPjKNhILvJZ~@?~FNdE@dJE`ABzDDxFG~AExDOnJk@`CQ~A]NGhBpIxBpLH`@Bp@@dACbBMvA?bACvCI~A?|QArBEzL?n@BBFPBx@ErF`C@??PAlCtC@N@`@RXH|Av@pAp@f@p@`@t@pAz@vAHLl@V`@TPLLRJXTnA\rALJLD@hCO`AKrG]~@CTILSFsADYVWP?RFv@h@|AfARDZPlATr@H|BNlDDtA?r@@x@COjGW^AxCBH@FXAnBGdEE|FK@`@BfQFpD', 0);
INSERT INTO `LatLongs` VALUES(12.9280212, 77.6267905, 1485323300, '0.1 km', '1 min', 'Head south on 12th Main Rd toward 3rd Cross RdPass by the park (on the left)', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9270734, 77.6264824, 1485323300, '0.3 km', '1 min', 'Turn left onto 3rd Cross Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9261219, 77.628711, 1485323300, '0.2 km', '2 mins', 'Turn right onto 8th Main Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9244756, 77.6283014, 1485323300, '51 m', '1 min', 'Turn left onto Sarjapur Main Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9243283, 77.6287495, 1485323300, '1.0 km', '2 mins', 'Turn right onto Madivala Road', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9211226, 77.620322, 1485323300, '0.2 km', '1 min', 'Turn left onto Hosur RdPass by the gas station (on the left)', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9194817, 77.6213822, 1485323300, '0.3 km', '1 min', 'Slight left toward 100 Feet Ring Rd/Outer Ring Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9174183, 77.6229115, 1485323300, '0.7 km', '3 mins', 'Turn right onto 100 Feet Ring Rd/Outer Ring RdPass by Dusit BTM (on the right in 400&nbsp;m)', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9161958, 77.6169474, 1485323300, '0.1 km', '1 min', 'Turn left toward Tank Shore Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9152625, 77.616381, 1485323300, '0.4 km', '1 min', 'Continue onto Tank Shore RdDrive along the lake (on the left)', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9121228, 77.6158932, 1485323300, '0.1 km', '1 min', 'Turn right onto 4th Cross Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9122597, 77.6149312, 1485323300, '1.6 km', '4 mins', 'Turn left onto 29th Main RdPass by SAHS (Sree Annapoorna Hospitality Services) (on the right)', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9056235, 77.6059093, 1485323300, '0.2 km', '1 min', 'Continue onto 7th Cross Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9057759, 77.6038448, 1485323300, '35 m', '1 min', 'Turn left onto 4th Main Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9054613, 77.6038292, 1485323300, '0.2 km', '1 min', 'Turn right onto 7th Cross RdPass by Sakhii Hospital (on the left)', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.905461, 77.6019687, 1485323300, '0.3 km', '1 min', 'Turn right onto Bannerghatta Main Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9073004, 77.6005741, 1485323300, '0.8 km', '3 mins', 'Turn left onto 100 Feet Ring Rd/15th Cross Rd/Outer Ring RdPass by HDFC Bank (on the left)', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9062664, 77.5934777, 1485323300, '0.1 km', '1 min', 'Turn left onto 12th Main Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9053269, 77.5934366, 1485323300, '0.1 km', '1 min', 'Turn right onto 17th A Cross Rd', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9053653, 77.5923085, 1485323300, '0.2 km', '1 min', 'Turn left onto 14th Main RdDestination will be on the right', 'c_|mAmnxxM|D|@r@yBbBgFd@{AXBtBX~Cj@VFyAL[F@^PdBzKdC`RNv@Xx@~B~EpBzDbApClFsCh@]n@a@T_@b@_@xA_AzBsAxAs@p@i@RMVdAnAdGdA|ETr@NnABrDFnD?bDfAb@rBlAZHH?|G`@xBTtD^O|AK`BX@f@FzBb@|AX|DVpC~@pBp@jGnBlBf@dDbAbBh@v@PNDTAb@u@pJWnBWv@s@jBQj@Eb@Dh@Hb@L~@VvGKzEQ|DErA~@@?rJ@NG@QB[Fi@qGzEdCvL|ApIFl@Af@Bp@CbBMbBCnEI~AtA@r@?p@D?zAAlAEv@fABjBPbDHXA', 0);
INSERT INTO `LatLongs` VALUES(12.9280212, 77.6267905, 1492060012, '0.1 km', '1 min', 'Head south on 12th Main Rd toward 3rd Cross RdPass by the park (on the left)', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 0);
INSERT INTO `LatLongs` VALUES(12.9270734, 77.6264824, 1492060012, '0.3 km', '1 min', 'Turn right onto 3rd Cross Rd', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 1);
INSERT INTO `LatLongs` VALUES(12.9280955, 77.6239764, 1492060012, '0.2 km', '1 min', 'Turn left onto 16th Main Rd', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 2);
INSERT INTO `LatLongs` VALUES(12.926561, 77.6234236, 1492060012, '0.4 km', '1 min', 'Turn left onto Sarjapur Main Rd', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 3);
INSERT INTO `LatLongs` VALUES(12.9251243, 77.6267367, 1492060012, '0.7 km', '2 mins', 'Make a U-turn', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 4);
INSERT INTO `LatLongs` VALUES(12.9274315, 77.6209858, 1492060012, '0.5 km', '2 mins', 'Turn left after Indian Institute of Astrophysics (on the left)Pass by Kendriya Sadan (on the left)', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 5);
INSERT INTO `LatLongs` VALUES(12.9246164, 77.6182742, 1492060012, '0.3 km', '1 min', 'Turn right onto Hosur RdPass by Masjid-E-Noor (on the right)', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 6);
INSERT INTO `LatLongs` VALUES(12.9269385, 77.6165594, 1492060012, '0.1 km', '1 min', 'Turn left after Venkateshwara Hospital (on the left)', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 7);
INSERT INTO `LatLongs` VALUES(12.9264327, 77.6156533, 1492060012, '9 m', '1 min', 'Turn right onto 3rd Cross Rd', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 8);
INSERT INTO `LatLongs` VALUES(12.926468, 77.6155768, 1492060012, '0.8 km', '4 mins', 'Turn left onto Maruthi Nagar Main RdPass by Shanthi Sagar (on the right)', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 9);
INSERT INTO `LatLongs` VALUES(12.9196184, 77.6129515, 1492060012, '0.3 km', '1 min', 'Turn right at Gangothri Cir onto 60 Feet Rd/8th Cross Rd', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 10);
INSERT INTO `LatLongs` VALUES(12.9197639, 77.6103341, 1492060012, '0.4 km', '1 min', 'Turn left onto 16th Main Rd/Tavarekere Main RdPass by the park (on the right)', 'c_|mAmnxxM|D|@}@|CoCtInCp@bD|@~GwSNFeCpHs@bB_D`KcC|ItIhCf@f@r@Zr@~@rCPr@fAXj@wBhA_ClAU@UPgB`A}Az@`@`AbArBGLl@Fx@JfCj@hAZvBd@vA`@t@PjATlA^jAd@lAl@~At@|@XN|@Vh@Rr@RnBb@`@DAVCxBIvCG`CC~A|ABfHPtFP', 11);

-- --------------------------------------------------------

--
-- Table structure for table `Login`
--

CREATE TABLE `Login` (
  `username` text NOT NULL,
  `phonenumber` text NOT NULL,
  `email` text NOT NULL,
  `password` text NOT NULL,
  `uniqueid` bigint(20) NOT NULL,
  `deviceToken` longtext NOT NULL,
  `deviceType` int(11) NOT NULL,
  PRIMARY KEY (`uniqueid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Login`
--

INSERT INTO `Login` VALUES('Kevin Vishal Saldanha', '9898765432', 'kevin.saldanha@tavant.com', '', 1481605618, 'e1746d48481a91b1d28ad970db10f4ef85478a565fdd28bd07633334c4cd7e98', 1);
INSERT INTO `Login` VALUES('Navanitha P', '9898765432', 'navanitha.p@tavant.com', '', 1481605623, 'ca9a8fc88395cc4201f7510a127c45f98e6b1c668c6e08f1e145c537bde76a32', 1);
INSERT INTO `Login` VALUES('Anusha Surendra', '9898765432', 'anusha.surendra@tavant.com', '', 1481792792, 'de8277d38fa23411af7cdda97d90104742289f76d8c43a8513f2ab59d613f68b', 1);

-- --------------------------------------------------------

--
-- Table structure for table `PoolTrip`
--

CREATE TABLE `PoolTrip` (
  `trip_path` longtext NOT NULL,
  `source_name` mediumtext NOT NULL,
  `destination_name` mediumtext NOT NULL,
  `time_leaving_source` mediumtext NOT NULL,
  `time_leaving_destination` mediumtext NOT NULL,
  `number_of_seats` int(11) NOT NULL,
  `traveller_type` int(11) NOT NULL,
  `trip_type` int(11) NOT NULL,
  `total_trip_time` mediumtext NOT NULL,
  `uniqueid_val` bigint(20) NOT NULL,
  `phonenumber_val` text NOT NULL,
  `email_val` text NOT NULL,
  `is_trip_live` int(11) NOT NULL,
  `source_lat` double NOT NULL,
  `source_lng` double NOT NULL,
  `destination_lat` double NOT NULL,
  `destination_lng` double NOT NULL,
  `total_trip_distance` mediumtext NOT NULL,
  `trip_via` mediumtext NOT NULL,
  `day1` int(11) NOT NULL,
  `day2` int(11) NOT NULL,
  `day3` int(11) NOT NULL,
  `day4` int(11) NOT NULL,
  `day5` int(11) NOT NULL,
  `day6` int(11) NOT NULL,
  `day7` int(11) NOT NULL,
  `schedule_type` int(11) NOT NULL,
  `tripDate` varchar(25) NOT NULL,
  `isBooked` int(11) NOT NULL,
  `isPending` int(11) NOT NULL,
  `totalSeatsOffered` int(11) NOT NULL,
  `seatsBooked` int(11) NOT NULL,
  `bookiePhoneNumber` varchar(15) NOT NULL,
  PRIMARY KEY (`uniqueid_val`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `PoolTrip`
--

INSERT INTO `PoolTrip` VALUES('', 'No.12, CSRIE-II, Guava Garden Layout, 5th Block, Koramangala, 5th Block, Koramangala, Bengaluru, Karnataka 560095, India', '104, A-1 NGV, Sharavathi Block, National Games Village Complex, KHB Games Village, Koramangala, KHB Games Village, Koramangala, Bengaluru, Karnataka 560047, India', '09:00', '18:30', 6, 1, 1, '8 mins', 1481659833, '9898765432', 'kevin.saldanha@tavant.com', 1, 12.9337929, 77.6184343, 12.9462606, 77.6218629, '1.9 km\r\n', '20th Main Rd/Ganapathi Temple Rd and Adugodi Main Rd', 1, 1, 1, 1, 1, 0, 0, 1, '2016-Dec-14', 0, 1, 6, 4, '');
INSERT INTO `PoolTrip` VALUES('', 'Deralakatte, Someshwar, Karnataka, India', 'Mangaluru, Karnataka, India', '09:00', '18:30', 5, 2, 1, '31 mins', 1481721460, '9898765432', 'kevin.saldanha@tavant.com', 0, 12.8092366, 74.8947555, 12.9141417, 74.8559568, '17.6 km', 'Mangalore-Thokkottu-Konaje Univarsity Rd and NH66', 1, 1, 1, 1, 1, 0, 0, 1, '2016-Dec-14', 1, 0, 5, 0, '');
INSERT INTO `PoolTrip` VALUES('', 'Marathahalli, Bengaluru, Karnataka, India', 'gobal village mindtree limited, Santhosapuram, 1st Block Koramangala, HSR Layout 5th Sector, Bengaluru, Karnataka 560034, India', '09:00', '18:30', 1, 2, 1, '27 mins', 1481783214, '9898765432', 'navanitha.p@tavant.com', 1, 12.9591722, 77.697419, 12.9176507, 77.6233465, '11.4 km', 'NH44', 1, 1, 1, 1, 1, 0, 0, 2, '2016-Dec-15', 0, 0, 1, 0, '');
INSERT INTO `PoolTrip` VALUES('', 'JP Nagar, Bengaluru, Karnataka, India', 'Jayanagar East, Jaya Nagar 1st Block, Jayanagara Jaya Nagar, Bengaluru, Karnataka, India', '09:00', '18:30', 4, 1, 1, '11 mins', 1481787365, '9898765432', 'navanitha.p@tavant.com', 1, 12.910491, 77.5857168, 12.9329463, 77.5838692, '2.7 km', '9th Main Rd', 1, 1, 1, 1, 1, 0, 0, 2, '2016-Dec-15', 1, 0, 4, 0, '');
INSERT INTO `PoolTrip` VALUES('', 'No.12, CSRIE-II, Guava Garden Layout, 5th Block, Koramangala, 5th Block, Koramangala, Bengaluru, Karnataka 560095, India', 'JP Nagar 7th Phase, Bengaluru, Karnataka, India', '09:00', '18:30', 5, 1, 1, '36 mins', 1481792939, '9898765432', 'anusha.surendra@tavant.com', 1, 12.9337929, 77.6184343, 12.8873185, 77.5780751, '10.7 km', 'Bannerghatta Main Rd', 1, 1, 1, 1, 1, 0, 0, 1, '2016-Dec-15', 1, 0, 5, 0, '');
INSERT INTO `PoolTrip` VALUES('', 'No.12, CSRIE-II, Guava Garden Layout, 5th Block, Koramangala, 5th Block, Koramangala, Bengaluru, Karnataka 560095, India', 'JP Nagar 7th Phase, Bengaluru, Karnataka, India', '09:00', '18:30', 1, 1, 1, '36 mins', 1482039451, '9898765432', 'kevin.saldanha@tavant.com', 1, 12.9337929, 77.6184343, 12.8873185, 77.5780751, '10.7 km', 'Bannerghatta Main Rd', 1, 1, 1, 1, 1, 0, 0, 1, '2016-Dec-18', 0, 1, 1, 0, '');
INSERT INTO `PoolTrip` VALUES('', 'Koramangala, Bengaluru, Karnataka, India', '5th Phase, J P Nagar Phase 5, JP Nagar, Bengaluru, Karnataka 560078, India', '15:00', '18:30', 1, 1, 1, '24 mins', 1485323300, '9898765432', 'kevin.saldanha@tavant.com', 1, 12.9279232, 77.6271078, 12.903517, 77.5920295, '6.9 km', '29th Main Rd', 1, 1, 1, 1, 1, 0, 0, 2, '2017-Jan-25', 0, 0, 1, 0, '');
INSERT INTO `PoolTrip` VALUES('', '', '', '', '', 0, 0, 0, '', 1492059511, '', '', 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, '');
INSERT INTO `PoolTrip` VALUES('', 'Koramangala, Bengaluru, Karnataka, India', 'BTM Layout, Bengaluru, Karnataka, India', '09:00', '18:30', 1, 1, 2, '15 mins', 1492060012, '9898765432', 'kevin.saldanha@tavant.com', 1, 12.9279232, 77.6271078, 12.9165757, 77.6101163, '4.0 km', 'Sarjapur Main Rd', 1, 1, 1, 1, 1, 0, 0, 1, '2017-Oct-13', 0, 0, 1, 0, '');
